pipeline{
    agent {
        docker { 
            image 'maven:3.9.9-eclipse-temurin-21-alpine' 
        }
    }
     stages {
        stage('Setup') {
            steps {
                echo '-- Java & Maven versions --'
                sh 'java --version'
                sh 'mvn --version'
            }
        }
        stage('Build') {
            steps {
                echo '-- Build with Maven --'
                sh 'mvn clean compile'  
            }
        }
        stage('Test') {
            steps {
                echo '-- Run tests --'
                sh 'mvn test'
            }
        }
        stage('Package') {
            steps {
                echo '-- Create JAR/WAR --'
                sh 'mvn package'
            }
        }
    }
}