pipeline{
    agent {
        docker { 
            image 'node:24.14.1-alpine3.23' 
        }
    }
    stages{
        stage('Create'){
            steps{
                echo    '-- Create project --'
                sh      'npm init -y'
            }
        }
        stage('Test') {  
            steps {
                echo '-- Test Node version --'
                sh 'node --version'  
                sh 'npm --version'   
            }
        }
    }
}