pipeline{
    agent{
        docker { image 'node:22-alpine' }
    }
    stages{
        stage('Create'){
            steps{
                echo    '-- Create project --'
                sh      'npm init -y'
            }
        }
        stage('Test') {  
            steps {
                echo '-- Test Node version --'
                sh 'node --version'  
                sh 'npm --version'   
            }
        }
    }
}